---
jobs:
  ansible-lint:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.4.0
      - name: Lint Ansible
        uses: ./
        with:
          run: >
            rg --files-with-matches 'ansible.*:' --null |
            xargs --no-run-if-empty --null --
            ansible-lint

name: Ansible Lint

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .github/workflows/ansible-lint.yml
      - action.yml
      - requirements.core.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
      - tools/boot.yml
      - tools/devcontainer.yml
      - tools/docker.yml
  push:
    branches:
      - stable
    paths:
      - .github/workflows/ansible-lint.yml
      - action.yml
      - requirements.core.txt
      - requirements.txt
      - tools/action.py
      - tools/asyncio_cmd.py
      - tools/boot.yml
      - tools/devcontainer.yml
      - tools/docker.yml
  workflow_dispatch: ~
