---
jobs:
  yamllint:
    concurrency:
      cancel-in-progress: ${{ github.ref != 'refs/heads/stable' }}
      group: ${{ github.workflow }}-${{ github.ref }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint yaml code
        uses: ./
        with:
          run: >
            python tools/g_ls_tree.py yml |
            xargs --no-run-if-empty --null --
            yamllint -f github

name: YamlLint

# yamllint disable-line rule:truthy
on:
  pull_request:
    paths:
      - .github/workflows/yamllint.yml
      - "**.yml"
      - action.yml
      - requirements.txt
      - tools/action.py
      - tools/asyncio_as_completed.py
      - tools/asyncio_cmd.py
      - tools/g_ls_tree.py
  push:
    branches:
      - stable
    paths:
      - .github/workflows/yamllint.yml
      - "**.yml"
      - action.yml
      - requirements.txt
      - tools/action.py
      - tools/asyncio_as_completed.py
      - tools/asyncio_cmd.py
      - tools/g_ls_tree.py
  workflow_dispatch: ~
